{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import argparse\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "import os\n",
    "import pickle\n",
    "from data_loader import load_dataset_JM \n",
    "from model import MLP \n",
    "from torch.autograd import Variable \n",
    "import math\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)\nframe #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f4f00926193 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libc10.so)\nframe #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f4e8a3ea9eb in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch.so)\nframe #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f4e8a3ebc04 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch.so)\nframe #3: <unknown function> + 0x6c8b56 (0x7f4ed231eb56 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)\nframe #4: <unknown function> + 0x29660b (0x7f4ed1eec60b in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)\nframe #5: <unknown function> + 0x12529e (0x55bd5221329e in /usr/bin/python)\nframe #6: <unknown function> + 0x124e4a (0x55bd52212e4a in /usr/bin/python)\nframe #7: <unknown function> + 0xe262b (0x55bd521d062b in /usr/bin/python)\nframe #8: PyEval_EvalFrameEx + 0x523e (0x55bd521e6ebe in /usr/bin/python)\nframe #9: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #10: <unknown function> + 0x10cb29 (0x55bd521fab29 in /usr/bin/python)\nframe #11: <unknown function> + 0x12529e (0x55bd5221329e in /usr/bin/python)\nframe #12: <unknown function> + 0x124e4a (0x55bd52212e4a in /usr/bin/python)\nframe #13: <unknown function> + 0xe262b (0x55bd521d062b in /usr/bin/python)\nframe #14: PyEval_EvalFrameEx + 0x523e (0x55bd521e6ebe in /usr/bin/python)\nframe #15: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #16: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #17: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #18: PyEval_EvalFrameEx + 0x40bb (0x55bd521e5d3b in /usr/bin/python)\nframe #19: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #20: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #21: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #22: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #23: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #24: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #25: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #26: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #27: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #28: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #29: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #30: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #31: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #32: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #33: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #34: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #35: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #36: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #37: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #38: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #39: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #40: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #41: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #42: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #43: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #44: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #45: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #46: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #47: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #48: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #49: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #50: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #51: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #52: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #53: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #54: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #55: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #56: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #57: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #58: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #59: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #60: PyEval_EvalFrameEx + 0x40bb (0x55bd521e5d3b in /usr/bin/python)\nframe #61: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #62: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #63: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0mTraceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-58248f246646>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Load trained model for path generation\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mmlp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mMLP\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m42\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m7\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mmlp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload_state_dict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'models/mlp_100_4000_PReLU_ae_dd_final.pkl'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/home/zhao/.local/lib/python2.7/site-packages/torch/serialization.pyc\u001b[0m in \u001b[0;36mload\u001b[0;34m(f, map_location, pickle_module, **pickle_load_args)\u001b[0m\n\u001b[1;32m    525\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0m_open_file_like\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'rb'\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mopened_file\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    526\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0m_is_zipfile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mopened_file\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 527\u001b[0;31m             \u001b[0;32mwith\u001b[0m \u001b[0m_open_zipfile_reader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mopened_zipfile\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    528\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0m_load\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mopened_zipfile\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmap_location\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpickle_module\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mpickle_load_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    529\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0m_legacy_load\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mopened_file\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmap_location\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpickle_module\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mpickle_load_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/zhao/.local/lib/python2.7/site-packages/torch/serialization.pyc\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, name_or_buffer)\u001b[0m\n\u001b[1;32m    222\u001b[0m \u001b[0;32mclass\u001b[0m \u001b[0m_open_zipfile_reader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_opener\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    223\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname_or_buffer\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 224\u001b[0;31m         \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_open_zipfile_reader\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_C\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPyTorchFileReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname_or_buffer\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    225\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    226\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)\nframe #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f4f00926193 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libc10.so)\nframe #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f4e8a3ea9eb in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch.so)\nframe #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f4e8a3ebc04 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch.so)\nframe #3: <unknown function> + 0x6c8b56 (0x7f4ed231eb56 in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)\nframe #4: <unknown function> + 0x29660b (0x7f4ed1eec60b in /home/zhao/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)\nframe #5: <unknown function> + 0x12529e (0x55bd5221329e in /usr/bin/python)\nframe #6: <unknown function> + 0x124e4a (0x55bd52212e4a in /usr/bin/python)\nframe #7: <unknown function> + 0xe262b (0x55bd521d062b in /usr/bin/python)\nframe #8: PyEval_EvalFrameEx + 0x523e (0x55bd521e6ebe in /usr/bin/python)\nframe #9: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #10: <unknown function> + 0x10cb29 (0x55bd521fab29 in /usr/bin/python)\nframe #11: <unknown function> + 0x12529e (0x55bd5221329e in /usr/bin/python)\nframe #12: <unknown function> + 0x124e4a (0x55bd52212e4a in /usr/bin/python)\nframe #13: <unknown function> + 0xe262b (0x55bd521d062b in /usr/bin/python)\nframe #14: PyEval_EvalFrameEx + 0x523e (0x55bd521e6ebe in /usr/bin/python)\nframe #15: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #16: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #17: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #18: PyEval_EvalFrameEx + 0x40bb (0x55bd521e5d3b in /usr/bin/python)\nframe #19: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #20: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #21: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #22: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #23: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #24: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #25: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #26: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #27: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #28: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #29: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #30: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #31: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #32: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #33: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #34: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #35: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #36: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #37: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #38: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #39: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #40: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #41: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #42: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #43: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #44: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #45: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #46: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #47: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #48: <unknown function> + 0x10cdcc (0x55bd521fadcc in /usr/bin/python)\nframe #49: PyObject_Call + 0x3e (0x55bd521cb44e in /usr/bin/python)\nframe #50: PyEval_EvalFrameEx + 0x2c9f (0x55bd521e491f in /usr/bin/python)\nframe #51: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #52: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #53: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #54: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #55: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #56: PyEval_EvalFrameEx + 0x5986 (0x55bd521e7606 in /usr/bin/python)\nframe #57: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #58: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #59: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #60: PyEval_EvalFrameEx + 0x40bb (0x55bd521e5d3b in /usr/bin/python)\nframe #61: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\nframe #62: PyEval_EvalFrameEx + 0x541e (0x55bd521e709e in /usr/bin/python)\nframe #63: PyEval_EvalCodeEx + 0x6da (0x55bd521df98a in /usr/bin/python)\n"
     ]
    }
   ],
   "source": [
    "# Load trained model for path generation\n",
    "mlp = MLP(42, 7) \n",
    "mlp.load_state_dict(torch.load('models/mlp_100_4000_PReLU_ae_dd_final.pkl'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.17 (default, Nov 28 2022, 18:51:39) \n[GCC 7.5.0]"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
